services:
  api:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION: Host=database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      SERVER_KEY: ${SERVER_KEY}
      ADMIN_KEY: ${ADMIN_KEY}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: rebuild
          path: ./src
  # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 512M

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
