name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/build-push-action@v6

    - name: Build and run
      env:
        ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      run: |
        docker compose up --build -d

    - name: Verify services
      run: |
        docker ps
        docker compose logs

    - name: Prepare test directory
      run: mkdir -p test-results

    - name: Run k6 tests
      run: |
        docker run --rm \
          --network host \
          -v $PWD/tests/Load:/scripts \
          -v $PWD/test-results:/output \
          grafana/k6 run \
          --out json=/output/k6_results.json \
          --out csv=/output/k6_results.csv \
          /scripts/k6-script.js \
          --vus 10 \
          --duration 30s

    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: k6-test-results
        path: test-results/*
