name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dotnet:
    name: dotnet Build/Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Restore Dependencies
        run: dotnet restore ./src

      - name: Build .NET
        run: dotnet build ./src --configuration Release

      - name: Run .NET Tests
        run: dotnet test ./src/Tests --configuration Release