name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/build-push-action@v6

    - name: Build and run
      env:
        ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      run: |
        docker compose up --build -d

    - name: Verify services
      run: |
        docker ps
        docker compose logs
  load-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull k6 image
        run: docker pull grafana/k6
      - name: Run load test
        run: |
          docker run --add-host=host.docker.internal:host-gateway \
            -v $PWD/tests/Load:/scripts \
            grafana/k6 run /scripts/k6-script.test.ts \
            --vus 10 \
            --duration 30s
