name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/build-push-action@v6

    - name: Build and run
      env:
        ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      run: |
        export ADMIN_KEY="${ADMIN_KEY}"
        echo "::add-mask::$SERVER_KEY"
        echo "::add-mask::$ADMIN_KEY"
        echo "::add-mask::$DB_NAME"
        echo "::add-mask::$DB_USER"
        echo "::add-mask::$DB_PASSWORD"
        docker compose up -d --build

    - name: Verify services
      run: |
        docker ps

    - name: Setup Grafana k6
      uses: grafana/setup-k6-action@main

    - name: Run k6 tests
      env:
        SERVER_KEY: ${{ secrets.SERVER_KEY }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      run: |
        echo "::add-mask::$SERVER_KEY"
        echo "::add-mask::$ADMIN_KEY"
        k6 run \
          -e BASE_URL=http://127.0.0.1:8080 \
          -e SERVER_KEY="$SERVER_KEY" \
          -e ADMIN_KEY="$ADMIN_KEY" \
          --out csv=k6_results.csv \
          tests/Load/k6-script.test.ts \
          --vus 10 \
          --duration 30s

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k6-test-results
        path: k6_results.csv
